CREATE TABLE IF NOT EXISTS DEPARTMENTS(
EMPLOYEE_ID INTEGER,
NAME TEXT,
DEPARTMENT_ID INTEGER,
SALARY TEXT);

INSERT INTO DEPARTMENTS (EMPLOYEE_ID, NAME, DEPARTMENT_ID, SALARY)
VALUES
(223, 'David', 60, '$4400'),
(224, 'Zayn', 70, '$4500'),
(225, 'Jina', 60, '$4300'),
(226, 'Maxwell', 80, '$7400'),
(227, 'Jannik', 70, '$8100'),
(228, 'Aryna', 90, '$4800'),
(229, 'Madison', 90, '$4400'),
(230, 'Andrey', 100, '$5400'),
(231, 'Lewis', 100, '$2400');

SELECT DEPARTMENT_ID AS "DEPARTMENT_CODE",
COUNT(*) AS "NO. OF EMPLOYEES"
FROM DEPARTMENTS
GROUP BY DEPARTMENT_ID;

SELECT DEPARTMENT_ID, SUM(SALARY)
FROM DEPARTMENTS
GROUP BY DEPARTMENT_ID;

SELECT DEPARTMENT_ID AS "DEPARTMENT_CODE",
SUM(SALARY) AS "TOTAL SALARY"
FROM DEPARTMENTS
WHERE EMPLOYEE_ID = 224
GROUP BY DEPARTMENT_ID,

SELECT DEPARTMENT_ID COUNT(*) AS "BO. OF EMPLOYEES"
FROM DEPARTMENTS
GROUP BY DEPARTMENT_ID
HAVING COUNT(*)>2;